### ISSUE TITLE
new issue3

### ISSUE THREAD

**Issue by nanda32** [murugananthaml/logistics#41]
please start the issue
[1.1PC_WMS_MIS Report_0012_Stock Ledger_V 1 0.xlsx](https://github.com/murugananthaml/logistics/files/2149101/1.1PC_WMS_MIS.Report_0012_Stock.Ledger_V.1.0.xlsx)

**Comment by murugananthaml** [comment]
@Jeyapriyat , please start development

**Comment by Jeyapriyat** [comment]
i have doubt in debit note column

**Comment by nanda32** [comment]
clarified

**Comment by Jeyapriyat** [comment]
first five column finished . remaining column are pending

**Comment by Jeyapriyat** [comment]
these serial nos are pending 15,17,80

**Comment by murugananthaml** [comment]
@murugeshkumar-T , please finish the pending issues

**Comment by Jeyapriyat** [comment]
report finished please test

**Comment by nanda32** [comment]
[trigger transaction testing.xlsx](https://github.com/murugananthaml/logistics/files/2149145/trigger.transaction.testing.xlsx)
@Jeyapriyat  please close the testing issues

**Comment by Jeyapriyat** [comment]
issues fixed

**Comment by nanda32** [comment]
report working fine
